version : "3"
services:
  
  frontend:
    build: obesity-frontend/
    restart: always
    container_name: obesitytracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    build: obesity-backend/
    restart: always
    container_name: obesitytracker-backend
    depends_on:
      - db
      - fhir

  db:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: obesitytracker-db
    ports:
      - "3306:3306"
    volumes:
      - obesitytracker-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=obesitytracker
      - MYSQL_USER=obesitytracker_service
      - MYSQL_PASSWORD=obesitytrackerservicepassword

  fhir:
    # Already found this image that was on DockerHub so used this instead of a new one
    image: bradymiller/hapi-fhir-jpaserver-example:latest
    restart: always
    container_name: obesitytracker-fhir
    environment:
      JAVA_OPTIONS: "-Djetty.port=8081"
    ports:
      - "8081:8081"

volumes:
  obesitytracker-db:
