security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

spring:
  datasource:
    url: jdbc:mysql://db:3306/obesitytracker
    username: obesitytracker_service
    password: obesitytrackerservicepassword
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 25000
      max-active: 45
      max-idle: 25
      min-idle: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true

app:
  secret: mysecret
  token-validity-in-seconds: 2592000
  swagger-base: /api
  fhir-server: http://fhir:8081/baseDstu3

---

spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/obesitytracker
app:
  swagger-base: /
  fhir-server: http://localhost:8081/baseDstu3

---

usda:
  api:
    host: api.nal.usda.gov/ndb
    key: GFlWF4QPGi2j0hJBmjvgmCc2r8MeZBTDoUNAiiHy

logging:
  level:
    org.springframework.security: DEBUG
